# Generated by Django 5.2.8 on 2025-12-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobhunter', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='postition',
            new_name='position',
        ),
    ]
